title       : Mr0Wido's Blog
first_name  : Mr0Wido
description : This is my personal website. The purpose of the Website is to assist and monitor my own development.
baseurl     : "/" 
url         : "https://mr0wido.github.io" 

# Google Analytics
google_analytics: G-ZKD6SG72NE

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-minifier

search_enabled: true

disqus_shortname: mr0widos-blog
repo_theme_dark: transparent  


permalink: /:title/

paginate: 5
paginate_path: "/posts/page:num/"

sass:
  sass_dir: _sass
  style: compressed

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Sitemap settings
defaults:
  - scope:
      path: "assets/**/*.*"
    values:
      sitemap: false
  
jekyll-minifier:
  exclude: ['robots.txt']
  uglifier_args:
    harmony: true

  # Site Author
author:
  name             : "Mr0Wido's Blog"
  avatar           : "/assets/img/avatar.jpg"
  bio              : "I am an avid CTF player. I am interested in everything related to technology. I enjoy my time working with computers. Self and constant learner."
  location         : "Turkey"
  email            : "furkn.dniz@gmail.com"


  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://localhost:4000/"

    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Mr0Wido"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Mr0Wido"

    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/furkn.dniz/"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/furkan-deniz-0b4389267"


