title       : Mr0Wido's Blog
first_name  : Mr0Wido
description : "My blog website."
baseurl     : "/" 
url         : "https://mr0wido.github.io" 
lang        : "en"
icon        : "favicon.ico"


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-spaceship

search_enabled: true

disqus_shortname: mr0widos-blog
repo_theme_dark: transparent  


permalink: /:title/

paginate: 5
paginate_path: "/posts/page:num/"

sass:
  sass_dir: _sass
  style: compressed

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git


  # Site Author
author:
  name             : "Mr0Wido's Blog"
  avatar           : "/assets/img/avatar.jpg"
  bio              : "I am an avid CTF player. I am interested in everything related to technology. I enjoy my time working with computers. Self and constant learner."
  location         : "Turkey"
  email            : "furkn.dniz@gmail.com"
  
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://localhost:4000/"

    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Mr0Wido"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Mr0Wido"

    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/furkn.dniz/"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/furkan-deniz-0b4389267"


#Social
github_username: # your GitHub user name
gitlab_username: # your GitLab user name
twitter_username: # your Twitter handle
linkedin_username: # your LinkedIn user name
scholar_userid: # your Google Scholar ID
medium_username: # your Medium username
quora_username: # your Quora username
stackoverflow_id: # your stackoverflow id
spotify_id: # your spotify id
instagram_id: # your instagram id
facebook_id: # your facebook id
discord_id: # your discord id (18-digit unique numerical identifie


google_analytics:  # your Google Analytics measurement ID (format: G-XXXXXXXXXX)
google_site_verification:  # your google-site-verification ID (Google Search Console)